version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
    volumes:
      - node_modules:/app/node_modules
      - ./:/app

volumes:
  node_modules:
