version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:3000"
    environment:
      PORT: 3000
      APP_SOURCE_FOLDER: /opt/src
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      LOGIN_BASE_URL: "http://universalcharts.com:30100/api/rest/v1/"
  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data:
